<?php

namespace Project\FilmsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ORepository extends EntityRepository
{
}
